# Generated by Django 5.1.3 on 2024-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
